language: node_js
node_js: node
addons:
  apt:
    packages:
      - sshpass
before_deploy:
  - mkdir build
  - rm -rf node_modules
  - tar -czf package.tgz ./
  - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
  - scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:/var/www/deploy
  - ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/sh deploy.sh
  on:
    branch: master
env:
  global:
  - secure: NvwpHcqWUxRrOEZRKW18eH1bkNJWbrVLOt4hBFqo8MeTrcsNmyzEwMkSK0dD5VUAZ+H3fA5qKogGwjR1/ikuiFZCt47jF+ZWTcibH+rYL7WgKBQyK0/sYxE/3VwhlixZCJa6Mmmk7ct8TO/kiaUY2UhweE96U2wcl2NpiJa4vYxXqYpBdMTuGe+Cq0BLFlZJf3tQjx7AzXpFMJ+qtkZteM0HorDOPcPWhRHinbkRRZraxu9n6cC6niFFTfqLuqU/KakKOzEdMMVvkXDWo3124GlJSgLshdAxQ8UYa80stuTtCdwdYJADocdryfgyC9htBXD+pDtIS4ccybN/IE7uExMQFBWv5kIxMKU1hKqUBHgVBBgj7gLJUU4NdhfGv921KR86PRH8Zsj1NjyPAy72SyAEZv7aY32p2Ge/qOzia5hdV0eD8Q1cDGLLpgWgXNKxUf5aRg4wueIKPIO49ZIoRatlIytL5ZgS4/JMI4kSaJ2tuqQ32wWdihkvFWZoqaEXEJKU4ADkXOGfOARr2Frh0ddqrr9z93xOXIP/vsl4pAwzyvHoa7CESug8mQsTI3K3wVqBZY7GWE1kOCFMYr1CcalwWlpcVJn69b+m1Rz9OdhxqiieFiJ33TbblTtgY8hz6BqPjTGYm+AZXwLRShE+TIx0hWKOnFqoduTbdf0Scj8=
  - secure: crs19LUUbqk7HCCd2KqZTDZZ6chk/ajUo64rLE1w2niAblOSS2TukG5/X80e3+sPQeZOkiWv5sudAdWNTsWWbWHlbPpwqj4rAgsJ+NGDwkCJ8L758u0XKlKxz1U9vL7lhoEmw+T/m7Q0YvW18yJ4mnO2uGfnSiRIF94dwdyaW9lf5SK8uUp3z4OxA5vMYUeOBZ2f1XTsTcX3K1OkeOmogkpwM00biSxqyDdk/CY8cvzNd2RKoFL/nHJN9KrXAzfTs43pDOorMohMvOQYEn4H4pPM9m0EQ1QQjUenneGP0gcM76Tpx8NCmV2Qmj1RA6qipEaarbyvETTIxTRVqSoMH/DCGPrUQ8lGD1JiRV6aw0PvCcTA3uFdiGVq0ltSdNE9IEvulcvhIRoyjavmtwU7RpuYJMRJJUGKZmaYCzjE5W9uiBmxnkwVRHCf+PkqBUE4G9k/FD6yQ5BT5tF/dKrxwYj0yDW3CeNhfNw0dBGKbPJENaAf+n2TyhUUYgI+BZwa+4eAzXzFXY4vK9pk+f0ToaHC3eKizLLsRp8OXcB2GBJkgeLtSA+LZ8CVPAg3VfV2YnWe15zQV9LK1II489779wDolEayom6Ed/d1IQId1WwmAIlJjYedCv4Pm5qKzMHOMTeD8BzPVDkfl+mTbqFPGiqen6l4wKIaKLsjJ4VCBIQ=
