language: node_js
node_js: node
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/sh deploy.sh
  on:
    branch: master
env:
  global:
  - secure: NvwpHcqWUxRrOEZRKW18eH1bkNJWbrVLOt4hBFqo8MeTrcsNmyzEwMkSK0dD5VUAZ+H3fA5qKogGwjR1/ikuiFZCt47jF+ZWTcibH+rYL7WgKBQyK0/sYxE/3VwhlixZCJa6Mmmk7ct8TO/kiaUY2UhweE96U2wcl2NpiJa4vYxXqYpBdMTuGe+Cq0BLFlZJf3tQjx7AzXpFMJ+qtkZteM0HorDOPcPWhRHinbkRRZraxu9n6cC6niFFTfqLuqU/KakKOzEdMMVvkXDWo3124GlJSgLshdAxQ8UYa80stuTtCdwdYJADocdryfgyC9htBXD+pDtIS4ccybN/IE7uExMQFBWv5kIxMKU1hKqUBHgVBBgj7gLJUU4NdhfGv921KR86PRH8Zsj1NjyPAy72SyAEZv7aY32p2Ge/qOzia5hdV0eD8Q1cDGLLpgWgXNKxUf5aRg4wueIKPIO49ZIoRatlIytL5ZgS4/JMI4kSaJ2tuqQ32wWdihkvFWZoqaEXEJKU4ADkXOGfOARr2Frh0ddqrr9z93xOXIP/vsl4pAwzyvHoa7CESug8mQsTI3K3wVqBZY7GWE1kOCFMYr1CcalwWlpcVJn69b+m1Rz9OdhxqiieFiJ33TbblTtgY8hz6BqPjTGYm+AZXwLRShE+TIx0hWKOnFqoduTbdf0Scj8=